# Generated by Django 4.1.2 on 2022-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
